name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  jetx:
    path: ../
  jetx_annotations:
    path: ../packages/jetx_annotations
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  jetx_generator:
    path: ../packages/jetx_generator

flutter:
  uses-material-design: true
