include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unintended_html_in_doc_comment: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  language:
    strict-casts: false
    strict-raw-types: false

linter:
  rules:
    # Error rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    valid_regexps: true
    
    # Style rules
    always_declare_return_types: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_this: true
