targets:
  $default:
    builders:
      jetx_builder|jetx_builder:
        enabled: true

builders:
  jetx_builder:
    import: "package:jetx_builder/builder.dart"
    builder_factories: ["jetxBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: source
