builders:
  jetx_page_route_builder:
    import: "package:jetx_generator/builder.dart"
    builder_factories: ["jetPageRouteBuilder"]
    build_extensions: { ".dart": [".route.json"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["jetx_generator:jetx_router_builder"]

  jetx_router_builder:
    import: "package:jetx_generator/builder.dart"
    builder_factories: ["jetRouterBuilder"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: none
    build_to: source
    required_inputs: [".route.json"]

