import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

/// Matches `@JetRoute(...)` from the main `jetx` package without
/// requiring an import of jetx in this generator (the analyzer resolves
/// elements by URI).
const _annotationChecker = TypeChecker.fromUrl(
  'package:jetx/jet_navigation/src/routes/jet_route_annotation.dart#JetRoute',
);

/// Emits a `_$<ClassName>` mixin for every class annotated with
/// `@JetRoute(path: ...)`. The user's class extends [JetRouteData] and
/// mixes in the generated mixin to gain a working `location` getter.
///
/// Path parameter `:name` segments are matched by name against the
/// instance fields declared on the user's class. Fields not used in
/// the path become query parameters.
class JetRouteGenerator extends Generator {
  @override
  String generate(LibraryReader library, BuildStep buildStep) {
    final outputs = <String>[];
    for (final element in library.allElements) {
      if (element is! ClassElement) continue;
      final annotation = _annotationChecker.firstAnnotationOf(element);
      if (annotation == null) continue;
      outputs.add(_generateForClass(element, ConstantReader(annotation)));
    }
    return outputs.join('\n\n');
  }

  String _generateForClass(ClassElement cls, ConstantReader annotation) {
    final path = annotation.read('path').stringValue;
    final pathParams = _extractPathParams(path);
    final fields = cls.fields
        .where((f) => !f.isStatic && !f.isSynthetic && f.name != 'arguments')
        .toList();
    final fieldNames = fields.map((f) => f.name).toSet();

    for (final p in pathParams) {
      if (!fieldNames.contains(p)) {
        throw InvalidGenerationSourceError(
          'Path param ":$p" in "$path" has no matching field on ${cls.name}',
          element: cls,
        );
      }
    }

    final pathFields =
        fields.where((f) => pathParams.contains(f.name)).toList();
    final queryFields =
        fields.where((f) => !pathParams.contains(f.name)).toList();

    final pathParamMap = pathFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${pathFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';
    final queryParamMap = queryFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${queryFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';

    // Reify the field getters so the mixin can use them. Each becomes
    // an abstract getter; the user's class supplies the concrete
    // `final` field which satisfies it.
    final fieldGetters = fields.map((f) {
      final type = f.type.getDisplayString(withNullability: true);
      return '  $type get ${f.name};';
    }).join('\n');

    return '''
/// Generated by jetx_builder for [${cls.name}].
mixin _\$${cls.name} on JetRouteData {
$fieldGetters

  @override
  String get location => Jet.buildUrl(
        '$path',
        pathParams: $pathParamMap,
        queryParams: $queryParamMap,
      );
}
''';
  }

  List<String> _extractPathParams(String path) =>
      RegExp(r':(\w+)').allMatches(path).map((m) => m.group(1)!).toList();
}
