import 'package:analyzer/dart/element/element.dart';
import 'package:analyzer/dart/element/type.dart';
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

const _annotationChecker = TypeChecker.fromUrl(
  'package:jetx/jet_navigation/src/routes/jet_route_annotation.dart#JetRoute',
);

const _widgetChecker = TypeChecker.fromUrl(
  'package:flutter/src/widgets/framework.dart#Widget',
);

/// Generator for `@JetRoute(...)`. Two output shapes depending on the
/// annotated class:
///
/// 1. **Widget pages** — class extends `Widget`. Emits both:
///    - `<ClassName>Route extends JetRouteData` typed-navigation class
///      built from the widget's constructor params (skipping `key`).
///    - `<className>Jet` `final JetPage` constant pre-wired with
///      `bindings`, `middlewares`, `transition`, and
///      `fullscreenDialog` declared on the annotation. The widget is
///      reconstructed at push time from `Jet.parameters`.
///
/// 2. **Route specs** — class extends `JetRouteData` with the
///    `_$<ClassName>` mixin, no Widget ancestry. Emits the mixin only
///    (legacy form, unchanged from earlier jetx_builder revisions).
class JetRouteGenerator extends Generator {
  @override
  String generate(LibraryReader library, BuildStep buildStep) {
    final outputs = <String>[];
    for (final element in library.allElements) {
      if (element is! ClassElement) continue;
      final annotation = _annotationChecker.firstAnnotationOf(element);
      if (annotation == null) continue;
      final reader = ConstantReader(annotation);
      if (_widgetChecker.isAssignableFrom(element)) {
        outputs.add(_generateForWidget(element, reader));
      } else {
        outputs.add(_generateForSpec(element, reader));
      }
    }
    return outputs.join('\n\n');
  }

  // ------------------------------------------------------------------
  // Spec form (existing behavior)
  // ------------------------------------------------------------------

  String _generateForSpec(ClassElement cls, ConstantReader annotation) {
    final path = annotation.read('path').stringValue;
    final pathParams = _extractPathParams(path);
    final fields = cls.fields
        .where((f) => !f.isStatic && !f.isSynthetic && f.name != 'arguments')
        .toList();
    final fieldNames = fields.map((f) => f.name).toSet();

    for (final p in pathParams) {
      if (!fieldNames.contains(p)) {
        throw InvalidGenerationSourceError(
          'Path param ":$p" in "$path" has no matching field on ${cls.name}',
          element: cls,
        );
      }
    }

    final pathFields =
        fields.where((f) => pathParams.contains(f.name)).toList();
    final queryFields =
        fields.where((f) => !pathParams.contains(f.name)).toList();

    final pathParamMap = pathFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${pathFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';
    final queryParamMap = queryFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${queryFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';

    final fieldGetters = fields.map((f) {
      final type = f.type.getDisplayString(withNullability: true);
      return '  $type get ${f.name};';
    }).join('\n');

    return '''
/// Generated by jetx_builder for [${cls.name}] (route-spec form).
mixin _\$${cls.name} on JetRouteData {
$fieldGetters

  @override
  String get location => Jet.buildUrl(
        '$path',
        pathParams: $pathParamMap,
        queryParams: $queryParamMap,
      );
}
''';
  }

  // ------------------------------------------------------------------
  // Widget-page form (new in P5)
  // ------------------------------------------------------------------

  String _generateForWidget(ClassElement cls, ConstantReader annotation) {
    final path = annotation.read('path').stringValue;
    final pathParams = _extractPathParams(path);

    final bindingTypes = annotation
        .read('bindings')
        .listValue
        .map((dv) => dv.toTypeValue()!.element!.name!)
        .toList();
    final middlewareTypes = annotation
        .read('middlewares')
        .listValue
        .map((dv) => dv.toTypeValue()!.element!.name!)
        .toList();
    final fullscreenDialog = annotation.read('fullscreenDialog').boolValue;
    final transitionLiteral = _transitionLiteral(annotation.read('transition'));

    final ctor = cls.unnamedConstructor;
    if (ctor == null) {
      throw InvalidGenerationSourceError(
        '${cls.name} must declare an unnamed constructor for @JetRoute.',
        element: cls,
      );
    }

    final params =
        ctor.parameters.where((p) => p.name != 'key').toList(growable: false);
    final paramNames = params.map((p) => p.name).toSet();

    for (final p in pathParams) {
      if (!paramNames.contains(p)) {
        throw InvalidGenerationSourceError(
          'Path param ":$p" in "$path" has no matching constructor '
          'param on ${cls.name}',
          element: cls,
        );
      }
    }

    final pathFields = params.where((p) => pathParams.contains(p.name)).toList();
    final queryFields =
        params.where((p) => !pathParams.contains(p.name)).toList();

    final routeClassName = '${cls.name}Route';
    final routeCtorParamsBody = params
        .map((p) {
          final isRequired = !_isNullable(p.type);
          return '${isRequired ? 'required ' : ''}this.${p.name}';
        })
        .join(', ');
    final routeCtorParams =
        routeCtorParamsBody.isEmpty ? '' : '{$routeCtorParamsBody}';
    final routeFieldDecls = params.map((p) {
      final type = p.type.getDisplayString(withNullability: true);
      return '  final $type ${p.name};';
    }).join('\n');

    final pathParamMap = pathFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${pathFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';
    final queryParamMap = queryFields.isEmpty
        ? 'const <String, Object?>{}'
        : '<String, Object?>{${queryFields.map((f) => "'${f.name}': ${f.name}").join(', ')}}';

    final widgetCtorArgs = params
        .map((p) => '${p.name}: ${_paramExtractor(p)}')
        .join(',\n      ');

    final pageVarName = _lowerFirst('${cls.name}Jet');

    final extras = <String>[];
    if (bindingTypes.isNotEmpty) {
      extras.add('  bindings: [${bindingTypes.map((t) => '$t()').join(', ')}],');
    }
    if (middlewareTypes.isNotEmpty) {
      extras.add(
          '  middlewares: [${middlewareTypes.map((t) => '$t()').join(', ')}],');
    }
    if (transitionLiteral != null) {
      extras.add('  transition: $transitionLiteral,');
    }
    if (fullscreenDialog) {
      extras.add('  fullscreenDialog: true,');
    }
    final extrasBlock = extras.isEmpty ? '' : '\n${extras.join('\n')}';

    final widgetCtorBody = params.isEmpty
        ? 'const ${cls.name}()'
        : '${cls.name}(\n      $widgetCtorArgs,\n    )';

    return '''
/// Generated by jetx_builder for [${cls.name}] (widget-page form).
class $routeClassName extends JetRouteData {
  const $routeClassName($routeCtorParams);

$routeFieldDecls

  @override
  String get location => Jet.buildUrl(
        '$path',
        pathParams: $pathParamMap,
        queryParams: $queryParamMap,
      );
}

/// Auto-registered JetPage for [${cls.name}]. Add to your app_pages
/// list (e.g. `getPages: [..., $pageVarName, ...]`).
final JetPage $pageVarName = JetPage(
  name: '$path',
  page: () => $widgetCtorBody,$extrasBlock
);
''';
  }

  // ------------------------------------------------------------------
  // helpers
  // ------------------------------------------------------------------

  List<String> _extractPathParams(String path) =>
      RegExp(r':(\w+)').allMatches(path).map((m) => m.group(1)!).toList();

  bool _isNullable(DartType type) =>
      type.nullabilitySuffix.toString().contains('question');

  /// Returns the concrete extractor expression for a single
  /// constructor parameter — pulled from `Jet.parameters` for v1.
  String _paramExtractor(ParameterElement p) {
    final type = p.type.getDisplayString(withNullability: true);
    final lit = "'${p.name}'";
    switch (type) {
      case 'String':
        return 'Jet.parameters[$lit] ?? \'\'';
      case 'String?':
        return 'Jet.parameters[$lit]';
      case 'int':
        return 'int.parse(Jet.parameters[$lit] ?? \'0\')';
      case 'int?':
        return '(Jet.parameters[$lit] == null ? null : int.tryParse(Jet.parameters[$lit]!))';
      case 'double':
        return 'double.parse(Jet.parameters[$lit] ?? \'0\')';
      case 'double?':
        return '(Jet.parameters[$lit] == null ? null : double.tryParse(Jet.parameters[$lit]!))';
      case 'bool':
        return "Jet.parameters[$lit] == 'true'";
      case 'bool?':
        return "(Jet.parameters[$lit] == null ? null : Jet.parameters[$lit] == 'true')";
      default:
        throw InvalidGenerationSourceError(
          'Unsupported @JetRoute constructor param type "$type" on '
          '${p.enclosingElement!.name}.${p.name}. v1 supports '
          'String, int, double, bool (+ nullable variants).',
          element: p,
        );
    }
  }

  /// Reads a `transition: Transition.fade` annotation field. Returns
  /// `null` when the field is null, otherwise `'Transition.<name>'`.
  String? _transitionLiteral(ConstantReader reader) {
    if (reader.isNull) return null;
    final name = reader.objectValue.getField('_name')?.toStringValue();
    if (name == null) return null;
    return 'Transition.$name';
  }

  String _lowerFirst(String s) =>
      s.isEmpty ? s : '${s[0].toLowerCase()}${s.substring(1)}';
}
