// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by jetx_builder.

part of 'app_router.dart';

// **************************************************************************
// JetXRouterGenerator
// **************************************************************************

// ignore_for_file: type=lint

/// Generated by jetx_builder for [HomePage].
class HomePageRoute extends JetRouteData {
  const HomePageRoute();

  @override
  String get location => Jet.buildUrl(
        '/home',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Generated by jetx_builder for [LoginPage].
class LoginPageRoute extends JetRouteData {
  const LoginPageRoute();

  @override
  String get location => Jet.buildUrl(
        '/login',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Generated by jetx_builder for [ProductDetailPage].
class ProductDetailPageRoute extends JetRouteData {
  const ProductDetailPageRoute({required this.id, this.tab});

  final String id;
  final String? tab;

  @override
  String get location => Jet.buildUrl(
        '/products/:id',
        pathParams: <String, Object?>{'id': id},
        queryParams: <String, Object?>{'tab': tab},
      );
}

/// Generated by jetx_builder for [ProductsPage].
class ProductsPageRoute extends JetRouteData {
  const ProductsPageRoute();

  @override
  String get location => Jet.buildUrl(
        '/products',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Auto-aggregated route table for [AppRouter]. Wire into
/// `JetMaterialApp(getPages: AppRouter.pages)`.
final List<JetPage> _$AppRouterPages = <JetPage>[
  JetPage(
    name: '/home',
    page: () => const HomePage(),
    transition: Transition.fadeIn,
  ),
  JetPage(
    name: '/login',
    page: () => const LoginPage(),
    transition: Transition.fadeIn,
  ),
  JetPage(
    name: '/products/:id',
    page: () => ProductDetailPage(
      id: Jet.parameters['id'] ?? '',
      tab: Jet.parameters['tab'],
    ),
    bindings: [ProductDetailBinding()],
    transition: Transition.rightToLeft,
  ),
  JetPage(
    name: '/products',
    page: () => const ProductsPage(),
    transition: Transition.rightToLeft,
  ),
];
