import 'package:jetx/jetx.dart';

import '../pages/home_page.dart';
import '../pages/login_page.dart';
import '../pages/products_page.dart';

/// Aggregated route table. Each entry is a `<className>Jet` constant
/// generated by `jetx_builder` from the page's `@JetRoute(...)`
/// annotation. Adding a new page is a two-step change: annotate the
/// widget, then add its generated constant here. The string path,
/// transition, bindings, and middlewares all come from the annotation
/// — no duplication between the widget file and this list.
abstract class AppPages {
  static final List<JetPage> pages = <JetPage>[
    loginPageJet,
    homePageJet,
    productsPageJet,
    productDetailPageJet,
  ];
}
