// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'typed_routes.dart';

// **************************************************************************
// JetRouteGenerator
// **************************************************************************

/// Generated by jetx_builder for [LoginRoute].
mixin _$LoginRoute on JetRouteData {
  @override
  String get location => Jet.buildUrl(
        '/login',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Generated by jetx_builder for [HomeRoute].
mixin _$HomeRoute on JetRouteData {
  @override
  String get location => Jet.buildUrl(
        '/home',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Generated by jetx_builder for [ProductsRoute].
mixin _$ProductsRoute on JetRouteData {
  @override
  String get location => Jet.buildUrl(
        '/products',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Generated by jetx_builder for [ProductDetailRoute].
mixin _$ProductDetailRoute on JetRouteData {
  String get id;
  String? get tab;

  @override
  String get location => Jet.buildUrl(
        '/products/:id',
        pathParams: <String, Object?>{'id': id},
        queryParams: <String, Object?>{'tab': tab},
      );
}
