import 'package:jetx/jetx.dart';

part 'typed_routes.g.dart';

/// Type-safe route descriptors generated by `jetx_builder`. Replaces
/// the legacy `AppRoutes.productDetailFor('123')` string-builder
/// pattern with `LoginRoute()`, `HomeRoute()`, `ProductsRoute()`,
/// `ProductDetailRoute(id: '123')`.
///
/// Run `dart run build_runner build` (or `... watch`) to regenerate
/// `typed_routes.g.dart` after editing any class in this file.

@JetRoute(path: '/login')
class LoginRoute extends JetRouteData with _$LoginRoute {
  const LoginRoute();
}

@JetRoute(path: '/home')
class HomeRoute extends JetRouteData with _$HomeRoute {
  const HomeRoute();
}

@JetRoute(path: '/products')
class ProductsRoute extends JetRouteData with _$ProductsRoute {
  const ProductsRoute();
}

@JetRoute(path: '/products/:id')
class ProductDetailRoute extends JetRouteData with _$ProductDetailRoute {
  const ProductDetailRoute({required this.id, this.tab});

  @override
  final String id;

  /// Optional tab to deep-link into. Becomes a `?tab=...` query param.
  @override
  final String? tab;
}
