name: auto_route_library

packages:
  - auto_route
  - auto_route_generator


command:
  bootstrap:
    usePubspecOverrides: true


scripts:
  analyze:
    exec: dart analyze .
  version-ar:
    exec: melos version


# alias version-ar='melos version --no-dependent-constraints --scope=auto_route'
# alias version-ar='melos publish --scope=auto_route'
