/// Public entry point used by `build.yaml`. Wraps the
/// `JetXRouterGenerator` aggregator in a [PartBuilder] so the
/// generated content lands in `<host>.g.dart` next to the host file
/// that carries the `@JetXRouter()` annotation.
library;

import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'src/jet_router_generator.dart';

Builder jetxBuilder(BuilderOptions options) => PartBuilder(
      [JetXRouterGenerator()],
      '.g.dart',
      header: '''// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by jetx_builder.
''',
    );
