// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'home_page.dart';

// **************************************************************************
// JetRouteGenerator
// **************************************************************************

/// Generated by jetx_builder for [HomePage] (widget-page form).
class HomePageRoute extends JetRouteData {
  const HomePageRoute();

  @override
  String get location => Jet.buildUrl(
        '/home',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Auto-registered JetPage for [HomePage]. Add to your app_pages
/// list (e.g. `getPages: [..., homePageJet, ...]`).
final JetPage homePageJet = JetPage(
  name: '/home',
  page: () => const HomePage(),
  transition: Transition.fadeIn,
);
