// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'login_page.dart';

// **************************************************************************
// JetRouteGenerator
// **************************************************************************

/// Generated by jetx_builder for [LoginPage] (widget-page form).
class LoginPageRoute extends JetRouteData {
  const LoginPageRoute();

  @override
  String get location => Jet.buildUrl(
        '/login',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Auto-registered JetPage for [LoginPage]. Add to your app_pages
/// list (e.g. `getPages: [..., loginPageJet, ...]`).
final JetPage loginPageJet = JetPage(
  name: '/login',
  page: () => const LoginPage(),
  transition: Transition.fadeIn,
);
