// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'products_page.dart';

// **************************************************************************
// JetRouteGenerator
// **************************************************************************

/// Generated by jetx_builder for [ProductsPage] (widget-page form).
class ProductsPageRoute extends JetRouteData {
  const ProductsPageRoute();

  @override
  String get location => Jet.buildUrl(
        '/products',
        pathParams: const <String, Object?>{},
        queryParams: const <String, Object?>{},
      );
}

/// Auto-registered JetPage for [ProductsPage]. Add to your app_pages
/// list (e.g. `getPages: [..., productsPageJet, ...]`).
final JetPage productsPageJet = JetPage(
  name: '/products',
  page: () => const ProductsPage(),
  transition: Transition.rightToLeft,
);

/// Generated by jetx_builder for [ProductDetailPage] (widget-page form).
class ProductDetailPageRoute extends JetRouteData {
  const ProductDetailPageRoute({required this.id, this.tab});

  final String id;
  final String? tab;

  @override
  String get location => Jet.buildUrl(
        '/products/:id',
        pathParams: <String, Object?>{'id': id},
        queryParams: <String, Object?>{'tab': tab},
      );
}

/// Auto-registered JetPage for [ProductDetailPage]. Add to your app_pages
/// list (e.g. `getPages: [..., productDetailPageJet, ...]`).
final JetPage productDetailPageJet = JetPage(
  name: '/products/:id',
  page: () => ProductDetailPage(
    id: Jet.parameters['id'] ?? '',
    tab: Jet.parameters['tab'],
  ),
  bindings: [ProductDetailBinding()],
  transition: Transition.rightToLeft,
);
